### ISSUE TITLE
Show turn and river with a delay in replay mode when players are all in

### ISSUE THREAD

**Issue by flavKT** [truenicoco/hh-creator#1]
[KTskippedturn.zip](https://github.com/truenicoco/hh-creator/files/4746711/KTskippedturn.zip)

Jai créé une hand history, un spot avec allin and call au flop,j'ai appuyé une seule fois sur "avancer" dans la main et la turn ET la river sont tombées en même temps.

**Comment by truenicoco** [comment]
SB est à tapis au flop, du coup il n'y plus d'autres actions possibles on est OK ?

**Comment by flavKT** [comment]
Oui,allin flop,l'action est close,mais plut^pot que dévoiler turn puis river,les 2 sont instantanément dévoilées en simultané
